export type EnglishPublicPage = {
  slug: string;
  turkishPath: string;
  title: string;
  seoTitle: string;
  description: string;
  lead: string;
  highlights: Array<{ title: string; text: string }>;
  sections: Array<{ title: string; paragraphs: string[] }>;
  faqs: Array<{ question: string; answer: string }>;
};

export const englishPublicPages: Record<string, EnglishPublicPage> = {
  "domestic-part-load-transport": {
    slug: "domestic-part-load-transport", turkishPath: "/yurtici-parsiyel-tasimacilik", title: "Domestic Part Load Transport", seoTitle: "Domestic Part Load Transport in Türkiye | REX Logistics", description: "Part load transport in Türkiye for palletised and commercial shipments. Request a tailored freight quote from REX Logistics.", lead: "For shipments that do not require a full vehicle, we organise planned part-load transport from collection to delivery across Türkiye.",
    highlights: [{ title: "From one pallet", text: "A practical option for commercial pallet loads." }, { title: "Address collection", text: "Collection can be planned from the sender's address." }, { title: "Nationwide delivery", text: "Delivery planning for provinces and districts across Türkiye." }],
    sections: [{ title: "A transport plan that fits your shipment", paragraphs: ["Part-load transport combines compatible shipments travelling on the same route. It can be a suitable option when a full vehicle is not required.", "We assess pallet count, dimensions, weight, packaging, collection point and delivery address together before planning the shipment."] }, { title: "Clear operational coordination", paragraphs: ["REX Logistics remains your single operational contact from collection planning through to delivery. Shipment details are evaluated to organise an appropriate transport solution.", "For growing volumes, we can also assess a vehicle-based alternative suited to the total load."] }],
    faqs: [{ question: "Can I send one pallet within Türkiye?", answer: "Part-load transport can be organised from one pallet, subject to the shipment details and route." }, { question: "Do you collect from our address?", answer: "Collection from the sender's address can be arranged as part of the transport plan." }],
  },
  "full-truckload-transport": {
    slug: "full-truckload-transport", turkishPath: "/komple-tasimacilik", title: "Full Truckload Transport", seoTitle: "Full Truckload Transport in Türkiye | REX Logistics", description: "Full truckload solutions for commercial and industrial shipments in Türkiye. Get a tailored quote from REX Logistics.", lead: "For commercial and industrial loads that require a full vehicle, we organise address-to-address transport based on your shipment plan.",
    highlights: [{ title: "Vehicle-based planning", text: "A transport model assessed for the total load." }, { title: "Collection and delivery", text: "Address details are included in the planning." }, { title: "Single point of contact", text: "One operational contact throughout the process." }],
    sections: [{ title: "When a full truckload is suitable", paragraphs: ["A full truckload may be appropriate when pallet count, volume, weight or delivery requirements make a dedicated vehicle-based solution more practical.", "The transport model is assessed using the shipment's dimensions, weight, route, loading readiness and delivery conditions."] }, { title: "Planned transport for commercial loads", paragraphs: ["We organise the collection and delivery stages around the confirmed shipment information. The plan is tailored to the load rather than relying on a one-size-fits-all service.", "Request a quote with your address, pallet or package count, dimensions and total weight for an accurate assessment."] }],
    faqs: [{ question: "How is full truckload pricing assessed?", answer: "Pricing depends on the route, total load, dimensions, weight, collection and delivery conditions." }, { question: "Can you collect from our premises?", answer: "Yes, collection from the sender's address can be organised after planning." }],
  },
  "international-road-freight": {
    slug: "international-road-freight", turkishPath: "/uluslararasi-karayolu-tasimaciligi", title: "International Road Freight", seoTitle: "International Road Freight Between Türkiye and Europe | REX Logistics", description: "Planned international road freight for part and full loads between Türkiye and Europe. Request a quote from REX Logistics.", lead: "We organise road freight solutions for part and full loads between Türkiye and Europe, based on route and shipment requirements.",
    highlights: [{ title: "Part and full loads", text: "Planning matched to your shipment volume." }, { title: "Türkiye and Europe", text: "International route-based coordination." }, { title: "Address-to-address", text: "Collection and delivery details are planned together." }],
    sections: [{ title: "International freight planning", paragraphs: ["International road transport requires the collection point, delivery point, cargo details and timing to be assessed together. We use this information to organise the appropriate transport flow.", "Part and full load options are evaluated according to the shipment's volume, weight and route."] }, { title: "A single operational contact", paragraphs: ["REX Logistics coordinates the transport process as your single operational contact. Provide complete cargo and address information so the most suitable option can be assessed.", "For shipments that need a faster alternative, an express solution may also be evaluated."] }],
    faqs: [{ question: "Do you organise part loads to Europe?", answer: "Part-load road freight can be assessed according to the route and shipment details." }, { question: "What information is needed for a quote?", answer: "Please share collection and delivery addresses, package or pallet count, dimensions, weight and cargo readiness date." }],
  },
  "air-freight": {
    slug: "air-freight", turkishPath: "/hava-kargo", title: "Air Freight", seoTitle: "International Air Freight | REX Logistics", description: "International air freight solutions planned around your cargo dimensions, weight, origin and destination. Request a quote from REX Logistics.", lead: "For international shipments, we assess dimensions, weight, origin and destination to organise an air freight solution suited to the cargo.",
    highlights: [{ title: "International shipments", text: "Solutions assessed for origin and destination." }, { title: "Cargo-based planning", text: "Dimensions and chargeable weight are evaluated." }, { title: "Clear quote process", text: "Share the essential cargo information first." }],
    sections: [{ title: "Air freight matched to the shipment", paragraphs: ["Air freight planning depends on the shipment's dimensions, actual weight, chargeable weight, origin, destination and readiness date.", "We evaluate these details before proposing an appropriate transport solution."] }, { title: "Prepare a precise request", paragraphs: ["A clear packing list, package dimensions and weight help us assess the right option. Special handling requirements should always be shared before a quote is prepared.", "REX Logistics coordinates the process as your single operational contact."] }],
    faqs: [{ question: "What do you need for an air freight quote?", answer: "Origin, destination, package count, dimensions, weight and cargo readiness date are the essential starting points." }, { question: "Can you collect the cargo?", answer: "Collection can be assessed as part of the planned shipment." }],
  },
  "express-courier": {
    slug: "express-courier", turkishPath: "/express-kargo", title: "International Express Courier", seoTitle: "International Express Courier | REX Logistics", description: "International express delivery to more than 220 countries and regions, including collection from abroad to Türkiye. Request a quote.", lead: "We organise international express shipments to more than 220 countries and regions, including collection solutions from abroad to Türkiye.",
    highlights: [{ title: "220+ countries and regions", text: "International express shipment coverage." }, { title: "From abroad to Türkiye", text: "Collection can be assessed from the origin address." }, { title: "Cargo details first", text: "Weight, dimensions and route guide the quote." }],
    sections: [{ title: "Express shipments internationally", paragraphs: ["International express transport is assessed using the origin, destination, package dimensions, weight and readiness date.", "For shipments from abroad to Türkiye, the collection address and cargo information are reviewed together before a transport option is organised."] }, { title: "Suitable for time-sensitive commercial parcels", paragraphs: ["Express is a route and cargo-specific solution, not a fixed promise for every item. Sharing clear shipment information helps us evaluate the appropriate option.", "REX Logistics is your single operational contact throughout the planning process."] }],
    faqs: [{ question: "Which destinations are covered?", answer: "International express solutions are available for more than 220 countries and regions, subject to shipment details." }, { question: "Can you arrange collection from abroad?", answer: "Yes, collection from abroad to Türkiye can be assessed using the origin address and cargo details." }],
  },
  "sea-freight": {
    slug: "sea-freight", turkishPath: "/denizyolu-tasimaciligi", title: "Sea Freight", seoTitle: "International Sea Freight: LCL and FCL | REX Logistics", description: "International LCL part-load and FCL full-container sea freight solutions. Request a tailored quote from REX Logistics.", lead: "For international cargo, we organise LCL part-load and FCL full-container sea freight solutions based on the shipment and route.",
    highlights: [{ title: "LCL part loads", text: "A solution for cargo that does not require a full container." }, { title: "FCL containers", text: "Container-based planning for full loads." }, { title: "Route assessment", text: "Origin, destination and cargo details guide the plan." }],
    sections: [{ title: "LCL and FCL options", paragraphs: ["LCL may be suitable for international cargo that does not require a full container, while FCL is assessed for loads that need container capacity.", "Cargo volume, weight, packaging, origin and destination are reviewed together to organise an appropriate option."] }, { title: "Plan before the cargo is ready", paragraphs: ["Providing the cargo readiness date and packing details early helps establish a practical sea freight plan.", "REX Logistics coordinates the relevant transport process as a single operational contact."] }],
    faqs: [{ question: "What is the difference between LCL and FCL?", answer: "LCL is for part-container cargo, while FCL is a full-container transport model. The appropriate option depends on the shipment." }, { question: "What is needed for a quote?", answer: "Please provide origin, destination, package details, dimensions, weight and cargo readiness date." }],
  },
  "warehousing-services": {
    slug: "warehousing-services", turkishPath: "/depolama", title: "Warehousing Services", seoTitle: "Warehousing, Stock Handling and Dispatch Preparation | REX Logistics", description: "Flexible logistics solutions for storage, stock tracking, handling and dispatch preparation. Contact REX Logistics.", lead: "We provide flexible logistics solutions for storage, stock tracking, handling and preparing cargo for dispatch.",
    highlights: [{ title: "Storage planning", text: "Solutions assessed around your operational needs." }, { title: "Stock visibility", text: "Stock tracking needs can be considered." }, { title: "Dispatch preparation", text: "Handling and preparation can be organised." }],
    sections: [{ title: "Flexible operational support", paragraphs: ["Storage requirements differ by product, volume, handling need and dispatch plan. We assess these elements to organise a suitable logistics solution.", "The service is planned around the cargo and operation; it does not imply ownership of a facility or network."] }, { title: "From storage to dispatch", paragraphs: ["Stock tracking, handling, labelling, packaging and dispatch preparation can be evaluated as part of an integrated workflow.", "Share the product type, quantity, storage period and dispatch expectations for a tailored assessment."] }],
    faqs: [{ question: "Can stock tracking be included?", answer: "Stock tracking needs can be evaluated as part of the planned logistics solution." }, { question: "Can cargo be prepared for dispatch?", answer: "Yes, handling and dispatch preparation can be assessed according to the cargo and operation." }],
  },
  "packing-and-handling": {
    slug: "packing-and-handling", turkishPath: "/paketleme-ellecleme", title: "Packing and Handling", seoTitle: "Packing, Labelling and Handling Services | REX Logistics", description: "Operational solutions for packing, labelling, palletising and preparing cargo for dispatch. Contact REX Logistics.", lead: "We organise operational solutions for packing, labelling, palletising and preparing cargo for dispatch.",
    highlights: [{ title: "Packing and labelling", text: "Preparation assessed around the cargo." }, { title: "Palletising", text: "A practical option for suitable commercial loads." }, { title: "Dispatch readiness", text: "Preparation can be coordinated with transport planning." }],
    sections: [{ title: "Cargo preparation before dispatch", paragraphs: ["Packing, labelling and palletising requirements are assessed according to the cargo's dimensions, packaging condition and transport plan.", "A clear preparation process supports an orderly handover into the transport workflow."] }, { title: "Handling planned around the operation", paragraphs: ["Handling needs vary by product and dispatch model. We evaluate the required operations before organising an appropriate solution.", "Share the product details, quantities and intended dispatch timing to begin the assessment."] }],
    faqs: [{ question: "Can cargo be palletised before dispatch?", answer: "Palletising can be assessed according to the cargo and planned transport operation." }, { question: "Can labels be applied?", answer: "Labelling requirements can be assessed as part of the preparation workflow." }],
  },
};

export const englishServiceSlugs = Object.keys(englishPublicPages);
