-- GPSLine parsiyel termin takvimi ve tahmini teslim tarihi hesaplama altyapısı.
CREATE TABLE IF NOT EXISTS public.supplier_transit_schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_code text NOT NULL,
  origin_region text NOT NULL,
  destination_region text NOT NULL,
  destination_city text NOT NULL,
  destination_district text NOT NULL,
  transit_business_days smallint NOT NULL CHECK (transit_business_days BETWEEN 1 AND 30),
  delivery_weekdays smallint[] NOT NULL CHECK (cardinality(delivery_weekdays) > 0),
  note text,
  source_document text NOT NULL,
  source_effective_date date NOT NULL,
  source_revision_date date,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT supplier_transit_schedules_weekdays_check
    CHECK (delivery_weekdays <@ ARRAY[1,2,3,4,5,6]::smallint[]),
  CONSTRAINT supplier_transit_schedules_route_unique
    UNIQUE (provider_code, origin_region, destination_region, destination_district, source_effective_date)
);

CREATE INDEX IF NOT EXISTS supplier_transit_schedules_lookup_idx
  ON public.supplier_transit_schedules(provider_code, origin_region, destination_region, destination_district)
  WHERE active;

ALTER TABLE public.supplier_transit_schedules ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.supplier_transit_schedules FROM PUBLIC, anon;
GRANT SELECT ON public.supplier_transit_schedules TO authenticated;

DROP POLICY IF EXISTS supplier_transit_schedules_read ON public.supplier_transit_schedules;
CREATE POLICY supplier_transit_schedules_read ON public.supplier_transit_schedules
  FOR SELECT TO authenticated
  USING (
    (public.rex_has_role(ARRAY['admin']) AND lower(coalesce(auth.jwt()->>'email',''))='info@rexlojistik.com')
    OR public.rex_has_permission('crm.sales_pipeline', 'view')
    OR public.rex_has_permission('operations.shipments', 'view')
  );

CREATE TABLE IF NOT EXISTS public.logistics_non_working_days (
  holiday_date date PRIMARY KEY,
  name text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.logistics_non_working_days ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.logistics_non_working_days FROM PUBLIC, anon;
GRANT SELECT ON public.logistics_non_working_days TO authenticated;
DROP POLICY IF EXISTS logistics_non_working_days_read ON public.logistics_non_working_days;
CREATE POLICY logistics_non_working_days_read ON public.logistics_non_working_days
  FOR SELECT TO authenticated
  USING (
    (public.rex_has_role(ARRAY['admin']) AND lower(coalesce(auth.jwt()->>'email',''))='info@rexlojistik.com')
    OR public.rex_has_permission('crm.sales_pipeline', 'view')
    OR public.rex_has_permission('operations.shipments', 'view')
  );

CREATE OR REPLACE FUNCTION public.rex_location_key(p_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT regexp_replace(
    translate(lower(coalesce(p_value, '')), 'çğıöşüâîû', 'cgiosuaiu'),
    '[^a-z0-9]+', '', 'g'
  )
$$;

CREATE OR REPLACE FUNCTION public.rex_add_logistics_business_days(p_start date, p_days integer)
RETURNS date
LANGUAGE plpgsql
STABLE
SET search_path = public, pg_temp
AS $$
DECLARE
  v_date date := p_start;
  v_added integer := 0;
BEGIN
  IF p_start IS NULL OR p_days IS NULL OR p_days < 0 THEN
    RAISE EXCEPTION 'Geçerli bir başlangıç tarihi ve gün sayısı gereklidir';
  END IF;
  WHILE v_added < p_days LOOP
    v_date := v_date + 1;
    IF extract(isodow FROM v_date)::integer BETWEEN 1 AND 5
       AND NOT EXISTS (
         SELECT 1 FROM public.logistics_non_working_days h
         WHERE h.holiday_date = v_date AND h.active
       ) THEN
      v_added := v_added + 1;
    END IF;
  END LOOP;
  RETURN v_date;
END;
$$;

CREATE OR REPLACE FUNCTION public.rex_gpsline_route_options(
  p_origin text DEFAULT NULL,
  p_destination text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_allowed boolean;
BEGIN
  v_allowed := (public.rex_has_role(ARRAY['admin']) AND lower(coalesce(auth.jwt()->>'email',''))='info@rexlojistik.com')
    OR public.rex_has_permission('crm.sales_pipeline', 'view')
    OR public.rex_has_permission('operations.shipments', 'view');
  IF NOT v_allowed THEN RAISE EXCEPTION 'Bu termin bilgisine erişim yetkiniz yok'; END IF;

  RETURN jsonb_build_object(
    'origins', COALESCE((
      SELECT jsonb_agg(value ORDER BY value)
      FROM (SELECT DISTINCT origin_region AS value FROM public.supplier_transit_schedules WHERE provider_code='gpsline' AND active) q
    ), '[]'::jsonb),
    'destinations', COALESCE((
      SELECT jsonb_agg(value ORDER BY value)
      FROM (
        SELECT DISTINCT destination_region AS value
        FROM public.supplier_transit_schedules
        WHERE provider_code='gpsline' AND active
          AND (NULLIF(trim(p_origin),'') IS NULL OR public.rex_location_key(origin_region)=public.rex_location_key(p_origin))
      ) q
    ), '[]'::jsonb),
    'districts', COALESCE((
      SELECT jsonb_agg(value ORDER BY value)
      FROM (
        SELECT DISTINCT destination_district AS value
        FROM public.supplier_transit_schedules
        WHERE provider_code='gpsline' AND active
          AND (NULLIF(trim(p_origin),'') IS NULL OR public.rex_location_key(origin_region)=public.rex_location_key(p_origin))
          AND (NULLIF(trim(p_destination),'') IS NULL OR public.rex_location_key(destination_region)=public.rex_location_key(p_destination))
      ) q
    ), '[]'::jsonb)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.rex_estimate_gpsline_delivery(
  p_origin text,
  p_destination text,
  p_district text,
  p_collection_date date
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_allowed boolean;
  v_route public.supplier_transit_schedules%ROWTYPE;
  v_base_date date;
  v_delivery_date date;
  v_safety integer := 0;
  v_weekday_names text[] := ARRAY['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'];
BEGIN
  v_allowed := (public.rex_has_role(ARRAY['admin']) AND lower(coalesce(auth.jwt()->>'email',''))='info@rexlojistik.com')
    OR public.rex_has_permission('crm.sales_pipeline', 'view')
    OR public.rex_has_permission('operations.shipments', 'view');
  IF NOT v_allowed THEN RAISE EXCEPTION 'Bu termin bilgisine erişim yetkiniz yok'; END IF;
  IF p_collection_date IS NULL THEN RAISE EXCEPTION 'Alım/planlama tarihi zorunludur'; END IF;

  SELECT * INTO v_route
  FROM public.supplier_transit_schedules s
  WHERE s.provider_code='gpsline' AND s.active
    AND public.rex_location_key(s.origin_region)=public.rex_location_key(p_origin)
    AND public.rex_location_key(s.destination_region)=public.rex_location_key(p_destination)
    AND (
      public.rex_location_key(s.destination_district)=public.rex_location_key(p_district)
      OR public.rex_location_key(regexp_replace(s.destination_district, '^'||s.destination_city||'\\s+', '', 'i'))=public.rex_location_key(p_district)
    )
  ORDER BY s.source_effective_date DESC
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'GPSLine termin listesinde bu çıkış, varış ve ilçe için eşleşme bulunamadı';
  END IF;

  v_base_date := public.rex_add_logistics_business_days(p_collection_date, v_route.transit_business_days);
  v_delivery_date := v_base_date;
  WHILE NOT (extract(isodow FROM v_delivery_date)::smallint = ANY(v_route.delivery_weekdays))
        OR EXISTS (SELECT 1 FROM public.logistics_non_working_days h WHERE h.holiday_date=v_delivery_date AND h.active)
  LOOP
    v_delivery_date := v_delivery_date + 1;
    v_safety := v_safety + 1;
    IF v_safety > 14 THEN RAISE EXCEPTION 'İlçe teslim günü hesaplanamadı'; END IF;
  END LOOP;

  RETURN jsonb_build_object(
    'provider_code', 'gpsline',
    'origin_region', v_route.origin_region,
    'destination_region', v_route.destination_region,
    'destination_city', v_route.destination_city,
    'destination_district', v_route.destination_district,
    'collection_date', p_collection_date,
    'planned_departure_date', p_collection_date + 1,
    'transit_business_days', v_route.transit_business_days,
    'base_route_date', v_base_date,
    'estimated_delivery_date', v_delivery_date,
    'adjusted_for_service_day', v_delivery_date <> v_base_date,
    'delivery_weekdays', to_jsonb(v_route.delivery_weekdays),
    'delivery_weekday_names', to_jsonb(ARRAY(SELECT v_weekday_names[d] FROM unnest(v_route.delivery_weekdays) d)),
    'note', v_route.note,
    'source_document', v_route.source_document,
    'source_effective_date', v_route.source_effective_date,
    'disclaimer', 'Tahmini teslim tarihidir. Resmî tatiller, mücbir sebepler, yol yasakları ve operasyonel engeller tarihi değiştirebilir.'
  );
END;
$$;

REVOKE ALL ON FUNCTION public.rex_location_key(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.rex_add_logistics_business_days(date,integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.rex_gpsline_route_options(text,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.rex_estimate_gpsline_delivery(text,text,text,date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rex_location_key(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rex_add_logistics_business_days(date,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rex_gpsline_route_options(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rex_estimate_gpsline_delivery(text,text,text,date) TO authenticated;

COMMENT ON TABLE public.supplier_transit_schedules IS 'Tedarikçi bazlı parsiyel rota/ilçe termin takvimleri';
COMMENT ON FUNCTION public.rex_estimate_gpsline_delivery(text,text,text,date) IS 'GPSLine kabul günü hariç iş günü süresini ve ilçe servis gününü uygulayarak tahmini teslim tarihini hesaplar';
